name: Build Linux

on:
  push:
    paths:
      - 'client/linux/**'
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libsdl2-dev

      - name: Build Terminal Client
        run: |
          cd client/linux/
          g++ -O3 -pthread ns-gamepad.cpp -o ns-gamepad -lSDL2

      - name: Build GUI Client (Dear ImGui)
        run: |
          cd client/linux/
          g++ -O3 -std=c++17 ns-gui.cpp \
            imgui.cpp imgui_draw.cpp imgui_tables.cpp imgui_widgets.cpp \
            backends/imgui_impl_sdl2.cpp backends/imgui_impl_sdlrenderer2.cpp \
            -o ns-gui -lpthread -lSDL2

      - uses: actions/upload-artifact@v6
        with:
          name: linux-gamepad
          path: client/linux/ns-gamepad

      - uses: actions/upload-artifact@v6
        with:
          name: linux-gui
          path: client/linux/ns-gui
